// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Shared {
    /// Describes the available authentication methods when connecting to the API.
    public enum Security {
        case accessToken(String)
    }}
