// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// Describes the available authentication methods when connecting to the API.
    public enum Security {
        case accessToken(String)
    }
}
