// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.


import Foundation

extension Operations.GetRecentlyAddedOptimizedForStreaming: Serializable {
    func serialize(with format: SerializableFormat) throws -> String {
        return ""
    }
}
