// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

func jsonEncoder() -> JSONEncoder {
    let jsonEncoder = JSONEncoder()
    // Sort keys to make this easier to test resulting JSON.
    jsonEncoder.outputFormatting = [.sortedKeys]
    return jsonEncoder
}

func serializeEncodable(_ encodable: Encodable?) throws -> String? {
    guard let encodable else { return nil }

    let data = try jsonEncoder().encode(encodable)
    return String(data: data, encoding: .utf8)
}
