workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
targets:
    plexswift:
        target: swift
        source: plexapi
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-swift-plexswift
