// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

/// Describes common parameters which can be used when making API requests.
///
/// > Note: These parameters may be overridden by individual API operations
public struct GlobalParameters {
    public let clientID: String?
    public let clientName: String?
    public let clientVersion: String?
    public let platform: String?
    public let deviceNickname: String?

    /// Creates an object with the given parameters
    ///
    /// - Parameter clientID: An opaque identifier unique to the client (UUID, serial number, or other unique device ID)
    /// - Parameter clientName: The name of the client application. (Plex Web, Plex Media Server, etc.)
    /// - Parameter clientVersion: The version of the client application.
    /// - Parameter deviceNickname: A relatively friendly name for the client device
    /// - Parameter platform: The platform of the client application.
    ///
    public init(
        clientID: String? = nil,
        clientName: String? = nil,
        clientVersion: String? = nil,
        platform: String? = nil,
        deviceNickname: String? = nil
    ) {
        self.clientID = clientID
        self.clientName = clientName
        self.clientVersion = clientVersion
        self.platform = platform
        self.deviceNickname = deviceNickname
    }
}

extension GlobalParameters: ParameterDefaults {
    public func defaultSerializedPathParameter(for key: String) throws -> String? {
        switch key {
        default: return nil
        }
    }

    public func defaultQueryParameter(for key: String) -> AnyValue? {
        switch key {
        default: return nil
        }
    }
}
