// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct Action {
        public let id: String
        public let key: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: String, key: String) {
            self.id = id
            self.key = key
        }
    }}

extension Operations.Action: Codable {
    enum CodingKeys: String, CodingKey {
        case id
        case key
    }
}

