// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct AddPlaylistContentsMediaContainer {
        public let leafCountAdded: Int?
        public let leafCountRequested: Int?
        public let metadata: [Operations.AddPlaylistContentsMetadata]?
        public let size: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(leafCountAdded: Int? = nil, leafCountRequested: Int? = nil, metadata: [Operations.AddPlaylistContentsMetadata]? = nil, size: Int? = nil) {
            self.leafCountAdded = leafCountAdded
            self.leafCountRequested = leafCountRequested
            self.metadata = metadata
            self.size = size
        }
    }}

extension Operations.AddPlaylistContentsMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case leafCountAdded
        case leafCountRequested
        case metadata = "Metadata"
        case size
    }
}

