// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct AddPlaylistContentsRequest: APIValue {
        /// the ID of the playlist
        @DecimalSerialized
        public private(set) var playlistID: Double
        /// the play queue to add to a playlist
        @DecimalSerialized
        public private(set) var playQueueID: Double
        /// the content URI for the playlist
        public let uri: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter playlistID: the ID of the playlist
        /// - Parameter playQueueID: the play queue to add to a playlist
        /// - Parameter uri: the content URI for the playlist
        ///
        public init(playlistID: Double, playQueueID: Double, uri: String) {
            self._playlistID = DecimalSerialized<Double>(wrappedValue: playlistID)
            self._playQueueID = DecimalSerialized<Double>(wrappedValue: playQueueID)
            self.uri = uri
        }
    }
}
extension Operations.AddPlaylistContentsRequest {
    var playlistIDWrapper: DecimalSerialized<Double> {
        return _playlistID
    }
    var playQueueIDWrapper: DecimalSerialized<Double> {
        return _playQueueID
    }
}
