// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct ApplyUpdatesRequest: APIValue {
        /// Indicate that the latest version should be marked as skipped. The <Release> entry for this version will have the `state` set to `skipped`.
        public let skip: Operations.Skip?
        /// Indicate that you want the update to run during the next Butler execution. Omitting this or setting it to false indicates that the update should install
        public let tonight: Operations.Tonight?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter skip: Indicate that the latest version should be marked as skipped. The <Release> entry for this version will have the `state` set to `skipped`.
        /// - Parameter tonight: Indicate that you want the update to run during the next Butler execution. Omitting this or setting it to false indicates that the update should install
        ///
        public init(skip: Operations.Skip? = nil, tonight: Operations.Tonight? = nil) {
            self.skip = skip
            self.tonight = tonight
        }
    }
}
