// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// The auto-select subtitle mode (0 = Manually selected, 1 = Shown with foreign audio, 2 = Always enabled)
    public enum AutoSelectSubtitle: String, Codable, APIValue {
        case zero = "0"
        case one = "1"
    }}
