// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct CreatePlaylistMediaContainer {
        public let metadata: [Operations.CreatePlaylistMetadata]?
        public let size: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(metadata: [Operations.CreatePlaylistMetadata]? = nil, size: Int? = nil) {
            self.metadata = metadata
            self.size = size
        }
    }
}

extension Operations.CreatePlaylistMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case metadata = "Metadata"
        case size
    }
}

