// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Indicate that you want to start download any updates found.
    public enum Download: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }
}
