// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Force the refresh even if the library is already being refreshed.
    public enum Force: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }}
