// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetAllMediaLibraryCollection {
        /// The user-made collection this media item belongs to
        public let tag: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter tag: The user-made collection this media item belongs to
        ///
        public init(tag: String) {
            self.tag = tag
        }
    }}

extension Operations.GetAllMediaLibraryCollection: Codable {
    enum CodingKeys: String, CodingKey {
        case tag
    }
}

