// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetAllLibrariesMediaContainer {
        public let allowSync: Bool
        public let directory: [Operations.GetAllLibrariesDirectory]
        public let size: Int
        public let title1: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(allowSync: Bool, directory: [Operations.GetAllLibrariesDirectory], size: Int, title1: String) {
            self.allowSync = allowSync
            self.directory = directory
            self.size = size
            self.title1 = title1
        }
    }}

extension Operations.GetAllLibrariesMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case allowSync
        case directory = "Directory"
        case size
        case title1
    }
}

