// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetAvailableClientsMediaContainer {
        public let server: [Operations.Server]?
        @DecimalSerialized
        public private(set) var size: Double?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(server: [Operations.Server]? = nil, size: Double? = nil) {
            self.server = server
            self._size = DecimalSerialized<Double?>(wrappedValue: size)
        }
    }
}

extension Operations.GetAvailableClientsMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case server = "Server"
        case size
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.server = try container.decodeIfPresent([Operations.Server].self, forKey: .server)
        self._size = try container.decodeIfPresent(DecimalSerialized<Double?>.self, forKey: .size) ?? DecimalSerialized<Double?>(wrappedValue: nil)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.server, forKey: .server)
        if self.size != nil {
            try container.encode(self._size, forKey: .size)
        }
    }
}

extension Operations.GetAvailableClientsMediaContainer {
    var sizeWrapper: DecimalSerialized<Double?> {
        return _size
    }
}
