// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetAllMediaLibraryCountry {
        /// The country of origin of this media item
        public let tag: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter tag: The country of origin of this media item
        ///
        public init(tag: String) {
            self.tag = tag
        }
    }}

extension Operations.GetAllMediaLibraryCountry: Codable {
    enum CodingKeys: String, CodingKey {
        case tag
    }
}

