// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
    /// 
    public struct GetAllMediaLibraryMeta {
        public let fieldType: [Operations.GetAllMediaLibraryFieldType]?
        public let type: [Operations.GetAllMediaLibraryType]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(fieldType: [Operations.GetAllMediaLibraryFieldType]? = nil, type: [Operations.GetAllMediaLibraryType]? = nil) {
            self.fieldType = fieldType
            self.type = type
        }
    }}

extension Operations.GetAllMediaLibraryMeta: Codable {
    enum CodingKeys: String, CodingKey {
        case fieldType = "FieldType"
        case type = "Type"
    }
}

