// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetAllLibrariesLocation {
        public let id: Int
        public let path: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: Int, path: String) {
            self.id = id
            self.path = path
        }
    }}

extension Operations.GetAllLibrariesLocation: Codable {
    enum CodingKeys: String, CodingKey {
        case id
        case path
    }
}

