// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Successful response containing media container data.
    public struct GetGenresLibraryResponseBody {
        public let mediaContainer: Operations.GetGenresLibraryMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetGenresLibraryMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }}

extension Operations.GetGenresLibraryResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

