// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetGlobalHubsMediaContainer {
        public let allowSync: Bool?
        public let hub: [Operations.Hub]?
        public let identifier: String?
        public let size: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(allowSync: Bool? = nil, hub: [Operations.Hub]? = nil, identifier: String? = nil, size: Int? = nil) {
            self.allowSync = allowSync
            self.hub = hub
            self.identifier = identifier
            self.size = size
        }
    }
}

extension Operations.GetGlobalHubsMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case allowSync
        case hub = "Hub"
        case identifier
        case size
    }
}

