// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetLibraryDirectory {
        public let key: String?
        public let prompt: String?
        public let search: Bool?
        public let secondary: Bool?
        public let title: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(key: String? = nil, prompt: String? = nil, search: Bool? = nil, secondary: Bool? = nil, title: String? = nil) {
            self.key = key
            self.prompt = prompt
            self.search = search
            self.secondary = secondary
            self.title = title
        }
    }
}

extension Operations.GetLibraryDirectory: Codable {
    enum CodingKeys: String, CodingKey {
        case key
        case prompt
        case search
        case secondary
        case title
    }
}

