// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetLibraryDetailsRequest: APIValue {
        /// The unique key of the Plex library. 
        /// Note: This is unique in the context of the Plex server.
        /// 
        public let sectionKey: Int
        /// Whether or not to include details for a section (types, filters, and sorts). 
        /// Only exists for backwards compatibility, media providers other than the server libraries have it on always.
        /// 
        public let includeDetails: Operations.IncludeDetails?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter sectionKey: The unique key of the Plex library. 
        /// Note: This is unique in the context of the Plex server.
        /// 
        /// - Parameter includeDetails: Whether or not to include details for a section (types, filters, and sorts). 
        /// Only exists for backwards compatibility, media providers other than the server libraries have it on always.
        /// 
        ///
        public init(sectionKey: Int, includeDetails: Operations.IncludeDetails? = nil) {
            self.sectionKey = sectionKey
            self.includeDetails = includeDetails
        }
    }}
