// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetLibraryItemsRequest: APIValue {
        /// The unique key of the Plex library. 
        /// Note: This is unique in the context of the Plex server.
        /// 
        public let sectionKey: Int
        /// A key representing a specific tag within the section.
        public let tag: Operations.Tag
        /// Adds the Guids object to the response
        /// 
        public let includeGuids: Operations.IncludeGuids?
        /// Adds the Meta object to the response
        /// 
        public let includeMeta: Operations.IncludeMeta?
        /// The type of media to retrieve.
        /// 1 = movie
        /// 2 = show
        /// 3 = season
        /// 4 = episode
        /// E.g. A movie library will not return anything with type 3 as there are no seasons for movie libraries
        /// 
        public let type: Operations.TypeModel?
        /// The number of items to return. If not specified, all items will be returned.
        /// If the number of items exceeds the limit, the response will be paginated.
        /// By default this is 50
        /// 
        public let xPlexContainerSize: Int?
        /// The index of the first item to return. If not specified, the first item will be returned.
        /// If the number of items exceeds the limit, the response will be paginated.
        /// By default this is 0
        /// 
        public let xPlexContainerStart: Int?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter sectionKey: The unique key of the Plex library. 
        /// Note: This is unique in the context of the Plex server.
        /// 
        /// - Parameter tag: A key representing a specific tag within the section.
        /// - Parameter includeGuids: Adds the Guids object to the response
        /// 
        /// - Parameter includeMeta: Adds the Meta object to the response
        /// 
        /// - Parameter type: The type of media to retrieve.
        /// 1 = movie
        /// 2 = show
        /// 3 = season
        /// 4 = episode
        /// E.g. A movie library will not return anything with type 3 as there are no seasons for movie libraries
        /// 
        /// - Parameter xPlexContainerSize: The number of items to return. If not specified, all items will be returned.
        /// If the number of items exceeds the limit, the response will be paginated.
        /// By default this is 50
        /// 
        /// - Parameter xPlexContainerStart: The index of the first item to return. If not specified, the first item will be returned.
        /// If the number of items exceeds the limit, the response will be paginated.
        /// By default this is 0
        /// 
        ///
        public init(sectionKey: Int, tag: Operations.Tag, includeGuids: Operations.IncludeGuids? = nil, includeMeta: Operations.IncludeMeta? = nil, type: Operations.TypeModel? = nil, xPlexContainerSize: Int? = nil, xPlexContainerStart: Int? = nil) {
            self.sectionKey = sectionKey
            self.tag = tag
            self.includeGuids = includeGuids
            self.includeMeta = includeMeta
            self.type = type
            self.xPlexContainerSize = xPlexContainerSize
            self.xPlexContainerStart = xPlexContainerStart
        }
    }}
