// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetLibraryItemsRequest: APIValue {
        /// the Id of the library to query
        public let sectionId: AnyValue
        /// A key representing a specific tag within the section.
        public let tag: Operations.Tag

        /// Creates an object with the specified parameters
        ///
        /// - Parameter sectionId: the Id of the library to query
        /// - Parameter tag: A key representing a specific tag within the section.
        ///
        public init(sectionId: AnyValue, tag: Operations.Tag) {
            self.sectionId = sectionId
            self.tag = tag
        }
    }
}
