// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetLibraryItemsSort {
        public let defaultDirection: String
        public let key: String
        public let title: String
        public let `default`: String?
        public let descKey: String?
        public let firstCharacterKey: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(defaultDirection: String, key: String, title: String, `default`: String? = nil, descKey: String? = nil, firstCharacterKey: String? = nil) {
            self.defaultDirection = defaultDirection
            self.key = key
            self.title = title
            self.`default` = `default`
            self.descKey = descKey
            self.firstCharacterKey = firstCharacterKey
        }
    }}

extension Operations.GetLibraryItemsSort: Codable {
    enum CodingKeys: String, CodingKey {
        case defaultDirection
        case key
        case title
        case `default` = "default"
        case descKey
        case firstCharacterKey
    }
}

