// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetMetaDataByRatingKeyMediaContainer {
        public let allowSync: Bool?
        public let identifier: String?
        public let librarySectionID: Int?
        public let librarySectionTitle: String?
        public let librarySectionUUID: String?
        public let mediaTagPrefix: String?
        public let mediaTagVersion: Int?
        public let metadata: [Operations.GetMetaDataByRatingKeyMetadata]?
        public let size: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(allowSync: Bool? = nil, identifier: String? = nil, librarySectionID: Int? = nil, librarySectionTitle: String? = nil, librarySectionUUID: String? = nil, mediaTagPrefix: String? = nil, mediaTagVersion: Int? = nil, metadata: [Operations.GetMetaDataByRatingKeyMetadata]? = nil, size: Int? = nil) {
            self.allowSync = allowSync
            self.identifier = identifier
            self.librarySectionID = librarySectionID
            self.librarySectionTitle = librarySectionTitle
            self.librarySectionUUID = librarySectionUUID
            self.mediaTagPrefix = mediaTagPrefix
            self.mediaTagVersion = mediaTagVersion
            self.metadata = metadata
            self.size = size
        }
    }}

extension Operations.GetMetaDataByRatingKeyMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case allowSync
        case identifier
        case librarySectionID
        case librarySectionTitle
        case librarySectionUUID
        case mediaTagPrefix
        case mediaTagVersion
        case metadata = "Metadata"
        case size
    }
}

