// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetMediaMetaDataCountry {
        /// The filter string for the country.
        public let filter: String
        /// The unique country identifier.
        public let id: Int
        /// The country name.
        public let tag: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter filter: The filter string for the country.
        /// - Parameter id: The unique country identifier.
        /// - Parameter tag: The country name.
        ///
        public init(filter: String, id: Int, tag: String) {
            self.filter = filter
            self.id = id
            self.tag = tag
        }
    }}

extension Operations.GetMediaMetaDataCountry: Codable {
    enum CodingKeys: String, CodingKey {
        case filter
        case id
        case tag
    }
}

