// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetMetaDataByRatingKeyResponse {
        case empty
        case badRequest(Operations.GetMetaDataByRatingKeyBadRequest)
        case object(Operations.GetMetaDataByRatingKeyResponseBody)
        case unauthorized(Operations.GetMetaDataByRatingKeyUnauthorized)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func badRequest() throws -> Operations.GetMetaDataByRatingKeyBadRequest {
            guard case .badRequest(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func object() throws -> Operations.GetMetaDataByRatingKeyResponseBody {
            guard case .object(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func unauthorized() throws -> Operations.GetMetaDataByRatingKeyUnauthorized {
            guard case .unauthorized(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }
    }}
