// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetMediaProvidersRequest: APIValue {
        /// Plex Authentication Token
        public let xPlexToken: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter xPlexToken: Plex Authentication Token
        ///
        public init(xPlexToken: String) {
            self.xPlexToken = xPlexToken
        }
    }}
