// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetMetadataChildrenDirectory {
        public let key: String?
        public let leafCount: Int?
        public let thumb: String?
        public let title: String?
        public let viewedLeafCount: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(key: String? = nil, leafCount: Int? = nil, thumb: String? = nil, title: String? = nil, viewedLeafCount: Int? = nil) {
            self.key = key
            self.leafCount = leafCount
            self.thumb = thumb
            self.title = title
            self.viewedLeafCount = viewedLeafCount
        }
    }
}

extension Operations.GetMetadataChildrenDirectory: Codable {
    enum CodingKeys: String, CodingKey {
        case key
        case leafCount
        case thumb
        case title
        case viewedLeafCount
    }
}

