// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// The on Deck content
    public struct GetOnDeckResponseBody {
        public let mediaContainer: Operations.GetOnDeckMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetOnDeckMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }
}

extension Operations.GetOnDeckResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

