// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
    public struct GetPlaylistsUnauthorized {
        public let errors: [Operations.GetPlaylistsPlaylistsErrors]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(errors: [Operations.GetPlaylistsPlaylistsErrors]? = nil) {
            self.errors = errors
        }
    }}

extension Operations.GetPlaylistsUnauthorized: Codable {
    enum CodingKeys: String, CodingKey {
        case errors
    }
}

