// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// returns all playlists
    public struct GetPlaylistsResponseBody {
        public let mediaContainer: Operations.GetPlaylistsMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetPlaylistsMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }
}

extension Operations.GetPlaylistsResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

