// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetRecentlyAddedLibraryResponse {
        case empty
        case badRequest(Operations.GetRecentlyAddedLibraryBadRequest)
        case object(Operations.GetRecentlyAddedLibraryResponseBody)
        case unauthorized(Operations.GetRecentlyAddedLibraryUnauthorized)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func badRequest() throws -> Operations.GetRecentlyAddedLibraryBadRequest {
            guard case .badRequest(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func object() throws -> Operations.GetRecentlyAddedLibraryResponseBody {
            guard case .object(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func unauthorized() throws -> Operations.GetRecentlyAddedLibraryUnauthorized {
            guard case .unauthorized(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }
    }}
