// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// List of Servers
    public struct GetServerListResponseBody {
        public let mediaContainer: Operations.GetServerListMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetServerListMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }
}

extension Operations.GetServerListResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

