// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetSessionsMediaContainer {
        public let metadata: [Operations.GetSessionsMetadata]?
        public let size: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(metadata: [Operations.GetSessionsMetadata]? = nil, size: Int? = nil) {
            self.metadata = metadata
            self.size = size
        }
    }}

extension Operations.GetSessionsMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case metadata = "Metadata"
        case size
    }
}

