// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
    public struct GetServerActivitiesActivitiesResponseBody {
        public let errors: [Operations.GetServerActivitiesErrors]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(errors: [Operations.GetServerActivitiesErrors]? = nil) {
            self.errors = errors
        }
    }
}

extension Operations.GetServerActivitiesActivitiesResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case errors
    }
}

