// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Bad Request - A parameter was not specified, or was specified incorrectly.
    public struct GetSearchAllLibrariesBadRequest {
        public let errors: [Operations.GetSearchAllLibrariesErrors]?

        /// Creates a request model with the specified parameters
        ///
        ///
        public init(errors: [Operations.GetSearchAllLibrariesErrors]? = nil) {
            self.errors = errors
        }
    }}

extension Operations.GetSearchAllLibrariesBadRequest: Codable {
    enum CodingKeys: String, CodingKey {
        case errors
    }
}

