// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Request Timeout
    public struct GetServerIdentityRequestTimeout {
        public let code: Int?
        public let message: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(code: Int? = nil, message: String? = nil) {
            self.code = code
            self.message = message
        }
    }}

extension Operations.GetServerIdentityRequestTimeout: Codable {
    enum CodingKeys: String, CodingKey {
        case code
        case message
    }
}

