// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// List of Plex Sessions
    public struct GetSessionHistoryResponseBody {
        public let mediaContainer: Operations.GetSessionHistoryMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetSessionHistoryMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }
}

extension Operations.GetSessionHistoryResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

