// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetServerActivitiesMediaContainer {
        public let activity: [Operations.Activity]?
        @DecimalSerialized
        public private(set) var size: Double?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(activity: [Operations.Activity]? = nil, size: Double? = nil) {
            self.activity = activity
            self._size = DecimalSerialized<Double?>(wrappedValue: size)
        }
    }
}

extension Operations.GetServerActivitiesMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case activity = "Activity"
        case size
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.activity = try container.decodeIfPresent([Operations.Activity].self, forKey: .activity)
        self._size = try container.decodeIfPresent(DecimalSerialized<Double?>.self, forKey: .size) ?? DecimalSerialized<Double?>(wrappedValue: nil)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.activity, forKey: .activity)
        if self.size != nil {
            try container.encode(self._size, forKey: .size)
        }
    }
}

extension Operations.GetServerActivitiesMediaContainer {
    var sizeWrapper: DecimalSerialized<Double?> {
        return _size
    }
}
