// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// List of Active Plex Sessions
    public struct GetSessionsResponseBody {
        public let mediaContainer: Operations.GetSessionsMediaContainer?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(mediaContainer: Operations.GetSessionsMediaContainer? = nil) {
            self.mediaContainer = mediaContainer
        }
    }}

extension Operations.GetSessionsResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case mediaContainer = "MediaContainer"
    }
}

