// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetTopWatchedContentGenre {
        public let filter: String?
        public let id: Int?
        public let tag: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(filter: String? = nil, id: Int? = nil, tag: String? = nil) {
            self.filter = filter
            self.id = id
            self.tag = tag
        }
    }
}

extension Operations.GetTopWatchedContentGenre: Codable {
    enum CodingKeys: String, CodingKey {
        case filter
        case id
        case tag
    }
}

