// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetTranscodeSessionsMediaContainer {
        public let size: Int?
        public let transcodeSession: [Operations.TranscodeSession]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(size: Int? = nil, transcodeSession: [Operations.TranscodeSession]? = nil) {
            self.size = size
            self.transcodeSession = transcodeSession
        }
    }}

extension Operations.GetTranscodeSessionsMediaContainer: Codable {
    enum CodingKeys: String, CodingKey {
        case size
        case transcodeSession = "TranscodeSession"
    }
}

