// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct GetTopWatchedContentCountry {
        public let filter: String?
        public let id: Int?
        public let tag: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(filter: String? = nil, id: Int? = nil, tag: String? = nil) {
            self.filter = filter
            self.id = id
            self.tag = tag
        }
    }}

extension Operations.GetTopWatchedContentCountry: Codable {
    enum CodingKeys: String, CodingKey {
        case filter
        case id
        case tag
    }
}

