// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum GetTranscodeSessionsResponse {
        case empty
        case badRequest(Operations.GetTranscodeSessionsBadRequest)
        case object(Operations.GetTranscodeSessionsResponseBody)
        case unauthorized(Operations.GetTranscodeSessionsUnauthorized)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func badRequest() throws -> Operations.GetTranscodeSessionsBadRequest {
            guard case .badRequest(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func object() throws -> Operations.GetTranscodeSessionsResponseBody {
            guard case .object(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }

        public func unauthorized() throws -> Operations.GetTranscodeSessionsUnauthorized {
            guard case .unauthorized(let value) = self else {
                throw PlexswiftError.missingResponseData
            }
            return value
        }
    }}
