// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Indicates if the user is part of a home group.
    public enum Home: Int, Codable, APIValue {
        case disable = 0
        case enable = 1
    }}
