// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// include external media in the results
    /// 
    public enum IncludeExternalMedia: Int, Codable, APIValue {
        case one = 1
        case zero = 0
    }
}
