// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Include IPv6 entries in the results
    public enum IncludeIPv6: Int, Codable, APIValue {
        case disable = 0
        case enable = 1
    }}
