// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// An integer log level to write to the PMS log with.  
    /// 0: Error  
    /// 1: Warning  
    /// 2: Info 
    /// 3: Debug  
    /// 4: Verbose
    /// 
    public enum Level: Int, Codable, APIValue {
        case zero = 0
        case one = 1
        case two = 2
        case three = 3
        case four = 4
    }
}
