// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public enum LibrarySectionID {
        case integer(Int)
        case string(String)
    }}

extension Operations.LibrarySectionID: Codable {
    public init(from decoder: Decoder) throws {
        if let value = try? Int(from: decoder) {
            self = .integer(value)
        } else if let value = try? String(from: decoder) {
            self = .string(value)
        } else {
            throw PlexswiftError.failedToHandleResponse(.failedToDecodeResponse)
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .integer(let value):
            try value.encode(to: encoder)
        case .string(let value):
            try value.encode(to: encoder)
        }
    }
}

