// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct MarkUnplayedRequest: APIValue {
        /// The media key to mark as Unplayed
        @DecimalSerialized
        public private(set) var key: Double

        /// Creates an object with the specified parameters
        ///
        /// - Parameter key: The media key to mark as Unplayed
        ///
        public init(key: Double) {
            self._key = DecimalSerialized<Double>(wrappedValue: key)
        }
    }
}
extension Operations.MarkUnplayedRequest {
    var keyWrapper: DecimalSerialized<Double> {
        return _key
    }
}
