// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct MediaProvider {
        public let feature: [Operations.Feature]?
        public let identifier: String?
        public let protocols: String?
        public let title: String?
        public let types: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(feature: [Operations.Feature]? = nil, identifier: String? = nil, protocols: String? = nil, title: String? = nil, types: String? = nil) {
            self.feature = feature
            self.identifier = identifier
            self.protocols = protocols
            self.title = title
            self.types = types
        }
    }}

extension Operations.MediaProvider: Codable {
    enum CodingKeys: String, CodingKey {
        case feature = "Feature"
        case identifier
        case protocols
        case title
        case types
    }
}

