// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// images are always scaled proportionally. A value of '1' in minSize will make the smaller native dimension the dimension resized against.
    public enum MinSize: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }}
