// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct Pivot {
        public let context: String?
        public let id: String?
        public let key: String?
        public let symbol: String?
        public let title: String?
        public let type: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(context: String? = nil, id: String? = nil, key: String? = nil, symbol: String? = nil, title: String? = nil, type: String? = nil) {
            self.context = context
            self.id = id
            self.key = key
            self.symbol = symbol
            self.title = title
            self.type = type
        }
    }}

extension Operations.Pivot: Codable {
    enum CodingKeys: String, CodingKey {
        case context
        case id
        case key
        case symbol
        case title
        case type
    }
}

