// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Your current mailing list status (active or unsubscribed)
    public enum PostUsersSignInDataMailingListStatus: String, Codable, APIValue {
        case active = "active"
        case unsubscribed = "unsubscribed"
    }}
