// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// type of playlists to return (default is all).
    public enum QueryParamSmart: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }
}
