// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Adds the Meta object to the response
    /// 
    public enum QueryParamIncludeMeta: Int, Codable, APIValue {
        case disable = 0
        case enable = 1
    }}
