// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// type of playlists to return (default is all).
    public enum QueryParamSmart: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }}
