// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct ResponseBody {
        public let baseURL: String
        public let identifier: String
        public let linkURL: String
        public let provides: String
        public let title: String
        /// The plex authtoken used to identify with
        public let token: String

        /// Creates an object with the specified parameters
        ///
        /// - Parameter token: The plex authtoken used to identify with
        ///
        public init(baseURL: String, identifier: String, linkURL: String, provides: String, title: String, token: String) {
            self.baseURL = baseURL
            self.identifier = identifier
            self.linkURL = linkURL
            self.provides = provides
            self.title = title
            self.token = token
        }
    }}

extension Operations.ResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case baseURL
        case identifier
        case linkURL
        case provides
        case title
        case token
    }
}

