// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// whether the playlist is smart or not
    public enum Smart: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }}
