// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct StatisticsMedia {
        public let accountID: Int?
        public let at: Int?
        public let count: Int?
        public let deviceID: Int?
        public let duration: Int?
        public let metadataType: Int?
        public let timespan: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(accountID: Int? = nil, at: Int? = nil, count: Int? = nil, deviceID: Int? = nil, duration: Int? = nil, metadataType: Int? = nil, timespan: Int? = nil) {
            self.accountID = accountID
            self.at = at
            self.count = count
            self.deviceID = deviceID
            self.duration = duration
            self.metadataType = metadataType
            self.timespan = timespan
        }
    }
}

extension Operations.StatisticsMedia: Codable {
    enum CodingKeys: String, CodingKey {
        case accountID
        case at
        case count
        case deviceID
        case duration
        case metadataType
        case timespan
    }
}

