// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// Current friend request status
    public enum Status: String, Codable, APIValue {
        case accepted = "accepted"
    }}
