// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct StopTaskRequest: APIValue {
        /// The name of the task to be started.
        public let taskName: Operations.PathParamTaskName

        /// Creates an object with the specified parameters
        ///
        /// - Parameter taskName: The name of the task to be started.
        ///
        public init(taskName: Operations.PathParamTaskName) {
            self.taskName = taskName
        }
    }}
