// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
    public struct StopAllTasksResponseBody {
        public let errors: [Operations.StopAllTasksErrors]?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(errors: [Operations.StopAllTasksErrors]? = nil) {
            self.errors = errors
        }
    }
}

extension Operations.StopAllTasksResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case errors
    }
}

