// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// the name of the task to be started.
    public enum TaskName: String, Codable, APIValue {
        case backupDatabase = "BackupDatabase"
        case buildGracenoteCollections = "BuildGracenoteCollections"
        case checkForUpdates = "CheckForUpdates"
        case cleanOldBundles = "CleanOldBundles"
        case cleanOldCacheFiles = "CleanOldCacheFiles"
        case deepMediaAnalysis = "DeepMediaAnalysis"
        case generateAutoTags = "GenerateAutoTags"
        case generateChapterThumbs = "GenerateChapterThumbs"
        case generateMediaIndexFiles = "GenerateMediaIndexFiles"
        case optimizeDatabase = "OptimizeDatabase"
        case refreshLibraries = "RefreshLibraries"
        case refreshLocalMedia = "RefreshLocalMedia"
        case refreshPeriodicMetadata = "RefreshPeriodicMetadata"
        case upgradeMediaAnalysis = "UpgradeMediaAnalysis"
    }}
