// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Indicate that you want the update to run during the next Butler execution. Omitting this or setting it to false indicates that the update should install
    public enum Tonight: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }
}
