// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// allow images to be resized beyond native dimensions.
    public enum Upscale: Int, Codable, APIValue {
        case zero = 0
        case one = 1
    }}
