// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct User {
        public let id: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: Int? = nil) {
            self.id = id
        }
    }}

extension Operations.User: Codable {
    enum CodingKeys: String, CodingKey {
        case id
    }
}

